version: "3"
services:
    house_finder_vpn:
        container_name: house_finder_vpn
        image: bubuntux/nordvpn
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.rp_filter=2
        devices:
            - /dev/net/tun
        environment:
            - USER=${NORD_VPN_USER}
            - PASS=${NORD_VPN_PASSWORD}
            - CONNECT=${NORD_VPN_COUNTRY}
            - TECHNOLOGY=NordLynx
            - DEBUG=on
        network_mode: bridge

    house_finder:
        container_name: house_finder
        image: python:3.9.0-alpine
        network_mode: bridge
        working_dir: /app
        command: /bin/sh -c "pip install -r requirements.txt && python -u main.py"
        volumes: 
            - ./:/app
        depends_on:
            - house_finder_vpn